# Generated by Django 4.2.5 on 2025-03-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('books_id', models.AutoField(primary_key=True, serialize=False)),
                ('books_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('course_enrolled', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('course_enrolled', models.CharField(max_length=20)),
                ('enrollment_date', models.DateField(max_length=20)),
            ],
        ),
    ]
