# Generated by Django 4.2.5 on 2025-03-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_rename_admin_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Admin',
        ),
    ]
