# Generated by Django 4.2.5 on 2025-03-26 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_rename_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
