# Generated by Django 4.2.5 on 2025-03-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_books_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='branch',
            field=models.CharField(default='Default Branch', max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='sname',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
